main/urls.py
from django.urls import path
from main.views import (
    show_main,
    create_product,
    show_xml,
    show_json,
    show_xml_by_id,
    show_json_by_id,
    register,
    login_user,
    logout_user,
    edit_product,
    delete_product,
    get_product_json,
    add_product_ajax,
    create_product_flutter,
)

app_name = "main"

urlpatterns = [
    path("", show_main, name="show_main"),
    path("create-product/", create_product, name="create_product"),
    path("xml/", show_xml, name="show_xml"),
    path("json/", show_json, name="show_json"),
    path("xml/<int:id>", show_xml_by_id, name="show_xml_by_id"),
    path("json/<int:id>", show_json_by_id, name="show_json_by_id"),
    path("register/", register, name="register"),
    path("login/", login_user, name="login"),
    path("logout", logout_user, name="logout"),
    path("edit-product/<int:id>", edit_product, name="edit_product"),
    path("delete/<int:id>", delete_product, name="delete_product"),
    path("get-product/", get_product_json, name="get_product_json"),
    path("create-product-ajax/", add_product_ajax, name="add_product_ajax"),
    path("create-flutter/", create_product_flutter, name="create_product_flutter"),
]

shopping_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("auth/", include("authentication.urls")),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class BaseModel(models.Model):
    objects = models.Manager()

    class Meta:
        abstract = True


class Product(BaseModel):
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    price = models.IntegerField()
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import Product


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description"]

main/views.py
from django.shortcuts import render
from main.forms import ProductForm
from django.views.decorators.csrf import csrf_exempt
from django.http import (
    HttpResponseRedirect,
    HttpResponse,
    HttpResponseNotFound,
    JsonResponse,
)
from django.urls import reverse
from main.models import Product
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import datetime
import json


@login_required(login_url="/login")
def show_main(request):
    product = Product.objects.filter(user=request.user)

    context = {
        "name": request.user.username,
        "class": "PBP F",
        "products": product,
        "last_login": request.COOKIES["last_login"],
    }
    return render(request, "main.html", context)


@login_required(login_url="/login")
def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse("main:show_main"))

    context = {"form": form}
    return render(request, "create-product.html", context)


def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(
        serializers.serialize("xml", data), content_type="application/xml"
    )


def show_json(request):
    data = Product.objects.all()
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", product_item))


def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(
        serializers.serialize("xml", data), content_type="application/xml"
    )


def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your account has been successfully created!")
            return redirect("main:login")
    context = {"form": form}
    return render(request, "register.html", context)


def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie("last_login", str(datetime.datetime.now()))
            return response
        else:
            messages.info(
                request, "Sorry, incorrect username or password. Please try again."
            )
    context = {}
    return render(request, "login.html", context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse("main:login"))
    response.delete_cookie("last_login")
    return response


@login_required(login_url="/login")
def edit_product(request, id):
    product = Product.objects.get(pk=id)
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse("main:show_main"))
    context = {"form": form}
    return render(request, "edit-product.html", context)


@login_required(login_url="/login")
def delete_product(request, id):
    product = Product.objects.get(pk=id)
    product.delete()
    return HttpResponseRedirect(reverse("main:show_main"))


@csrf_exempt
def add_product_ajax(request):
    if request.method == "POST":
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(
            name=name, price=price, description=description, user=user
        )
        new_product.save()

        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()


@csrf_exempt
def create_product_flutter(request):
    if request.method == "POST":
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user=request.user,
            name=data["name"],
            price=int(data["price"]),
            description=data["description"],
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create-product.html
{% extends "base.html" %} {% block content %}
    <h1>Add New Product</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Add Product" class="button"/>
                </td>
            </tr>
        </table>
    </form>
{% endblock content %}

main/templates/edit-product.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="p-2">
  <h1 class="title">Edit Product</h1>

  <form method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <tr>
        <td></td>
        <td>
          <input type="submit" value="Edit Product" />
        </td>
      </tr>
    </table>
  </form>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %} {% block meta %}
<title>Login</title>
{% endblock meta %} {% block content %}

<div class="login p-2">
  <h1 class='title'>Login</h1>

  <div class='d-flex flex-column pt-4 gap-4'>
    <form method="POST" action="">
        {% csrf_token %}
        <table>
          <tr>
            <td><p style="font-weight: bold">Username: &nbsp;</p></td>
            <td>
              <input
                type="text"
                name="username"
                placeholder="Username"
                class="form-control"
              />
            </td>
          </tr>
    
          <tr>
            <td><p style="font-weight: bold">Password: &nbsp;</p></td>
            <td>
              <input
                type="password"
                name="password"
                placeholder="Password"
                class="form-control"
              />
            </td>
          </tr>
            <td></td>
            <td class="d-flex justify-content-center">
              <input class="btn btn-primary w-100 mt-2" type="submit" value="Login" />
            </td>
          </tr>
        </table>
      </form>
    
      <div style="font-weight: normal; margin-top: 1rem">
        {% if messages %}
        <ul>
          {% for message in messages %}
          <li>{{ message }}</li>
          {% endfor %}
        </ul>
        {% endif %} Don't have an account yet?
        <a href="{% url 'main:register' %}">Register Now</a>
      </div>
    </div>
    
  </div>
  
{% endblock content %}

main/templates/main.html
{% extends "base.html" %} {% block content %}


    <nav class="navbar bg-dark">
        <div class="container-fluid">
        <a href="{% url 'main:show_main'%}" class="navbar-brand text-white font-weight-bold">{{name}}</a>
        <a href="{% url 'main:logout' %}">
            <button class="btn btn-primary">
                Logout
            </button>
        </a>
        </div>
    </nav>

    <div class="p-2">

        <h1 class='title'>Shopping List Page</h1>
        <hr>
        <h5 class='info'>Username: {{ name }}</h5>
        <h5 class='info'>Class: {{ class }}</h5>
    
        <h5 class='info'>Sesi Terakhir Login : {{ last_login }}</h5
        >
        <hr>
    
        <h2 style="margin-top: 50px;text-align: center;font-size:large;font-weight:bold;">Daftar Produk</h2>
    
    
        <div class="products">
            <table id="product_table" class='table text-center'></table> 
        </div>
    
    
        <br/>
    
    
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>

        <div class="button-section">
            
 
            <div class="product-button">
                <a href="{% url "main:create_product" %}">
                    <button class="btn btn-primary">Add New Product</button>
                </a>
            </div>
    
            <div class="logout-button">
              
            </div>
        </div>    
    </div>   

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="price" class="col-form-label">Price:</label>
                        <input type="number" class="form-control" id="price" name="price"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
</div>

<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }

    async function refreshProducts() {
        document.getElementById("product_table").innerHTML = ""
        const products = await getProducts()
        console.log(products)
        let htmlString = `<tr>
            <th>Name</th>
            <th>Price</th>
            <th>Description</th>
            <th>Date Added</th>
            <th>Action</th>
        </tr>`
        products.forEach((item) => {
            htmlString += `\n<tr>
            <td>${item.fields.name}</td>
            <td>${item.fields.price}</td>
            <td>${item.fields.description}</td>
            <td>${item.fields.date_added}</td>
            <td>
                <button id="edit-${item.pk}" class='btn btn-primary'>Edit</button> 
                <button id="delete-${item.pk}" class='btn btn-primary'>Delete</button></td>
        </tr>` 
        }
        ) 
        document.getElementById("product_table").innerHTML = htmlString
        products.forEach((item) => {
            document.getElementById(`edit-${item.pk}`).onclick = () => {
                window.location.href = `edit-product/${item.pk}`    
            }
            document.getElementById(`delete-${item.pk}`).onclick = () => {
                fetch(`delete/${item.pk}`).then(refreshProducts)
            }
        })
    }

    refreshProducts()

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }

    document.getElementById("button_add").onclick = addProduct

</script>


{% endblock content %}

main/templates/register.html
{% extends 'base.html' %} {% block meta %}
<title>Register</title>
{% endblock meta %} {% block content %}

<div class="login">
  <h1>Register</h1>

  <form method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <tr>
        <td></td>
        <td>
          <input type="submit" name="submit" value="Daftar"/ class="btn
          btn-primary">
        </td>
      </tr>
    </table>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>

{% endblock content %}